services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 'trading_platform.webapp:create_app()'
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/data/reports
    environment:
      - REPORTS_DIR=/app/data/reports
    env_file:
      - .env
  scheduler:
    build: .
    command: scheduler
    volumes:
      - ./data:/app/data
      - ./reports:/app/data/reports
    environment:
      - REPORTS_DIR=/app/data/reports
    env_file:
      - .env
volumes:
  reports:
