services:
  web:
    build: .
    command: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5000 'trading_platform.webapp:create_app()'
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
  scheduler:
    build: .
    command: scheduler
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  reports:
