services:
  web:
    build: .
    command: >
      gunicorn -k eventlet -b 0.0.0.0:8000 trading_platform.webapp:app
    ports:
      - "8000:8000"  # change left side to expose a different host port
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - models:/app/models
      # - .:/app  # uncomment for live reload during development
    environment:
      - FLASK_ENV=production
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  scheduler:
    build: .
    command: scheduler
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - models:/app/models
      # - .:/app  # uncomment for live reload during development
    environment:
      - FLASK_ENV=production
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Optional React front-end served via Nginx
  # Uncomment this block if `frontend/build` exists
  # frontend:
  #   image: nginx:alpine
  #   volumes:
  #     - ./frontend/build:/usr/share/nginx/html:ro
  #   ports:
  #     - "3000:80"  # change host port as needed
  #   depends_on:
  #     - web
volumes:
  reports:
  redis-data:
  models:
