version: "3.8"
services:
  web:
    build: .
    command: webapp
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    env_file:
      - .env
  scheduler:
    build: .
    command: scheduler
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    env_file:
      - .env
