services:
  web:
    build: .
    command: >
      gunicorn -k eventlet -b 0.0.0.0:8000 trading_platform.webapp:app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - models:/app/models
    environment:
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  scheduler:
    build: .
    command: scheduler
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - models:/app/models
    environment:
      - REPORTS_DIR=/app/reports
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  reports:
  redis-data:
  models:
