name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install -e .
      - name: Check PLAN_INDEX
        run: python scripts/gen_plan_index.py --check
      - name: Lint
        run: black . --check
      - name: Unit tests
        run: pytest -q

  docker-smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t tp .
      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name tp \
            -e POLYGON_API_KEY=dummy -e NEWS_API_KEY=dummy tp
          sleep 10
      - name: Curl metrics
        run: curl http://localhost:5000/api/metrics
      - name: Verify pipeline
        run: docker exec tp python -m trading_platform.run_daily --verify-only
