name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [lint, tests, smoke]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'pyproject.toml') }}"
          restore-keys: "${{ runner.os }}-pip-"
      - uses: docker/setup-buildx-action@v3
        if: matrix.target == 'smoke'
      - uses: actions/cache@v4
        if: matrix.target == 'smoke'
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}"
          restore-keys: "${{ runner.os }}-docker-"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install -e .
      - name: Check PLAN_INDEX
        run: python scripts/gen_plan_index.py --check
      - name: Lint
        if: matrix.target == 'lint'
        run: black . --check && flake8
      - name: Unit tests
        if: matrix.target == 'tests'
        run: pytest -q
      - name: Docker smoke
        if: matrix.target == 'smoke'
        run: |
          scripts/docker_smoke.sh --ci || { CODE=$?; [ $CODE -eq 78 ] || exit $CODE; }
